#!/usr/bin/env python3
import argparse
import sys

from gscore.cli.score import Score
from gscore.cli.train import Train
from gscore.cli.export import Export

if __name__ == '__main__':

    subcommands = []

    subcommands.extend(
        [
            Score(),
            Train(),
            Export()
        ]
    )

    parser = argparse.ArgumentParser()

    subparser = parser.add_subparsers(
        dest="subcommand",
        title="subcommands",
        description="CLI tools for scoring OSW files",
    )

    for subcommand in subcommands:
        subcommand.build_subparser(subparser)

    command = parser.parse_args()

    if command.subcommand:

        command.run(command)

    else:

        if len(sys.argv) == 1:

            parser.print_help()
